server:
  # 服务名称
  name: "ws_home"
  # 服务环境
  profile: "dev"
  # 服务监听地址
  port: 8080
  # 服务版本
  version: "v1.0.0"

# 日志配置
log:
  # 日志级别
  level: "debug"
  # 日志文件名 大小达到 max_size 后会自动分割，保留 max_age 天，最多保留 max_backups 个分割文件
  # 写满后自动新建日志文件命令： ws_home-2024-10-14T16-12-28.237.log
  file_name: "runtime/log/ws_home.log"
  # 日志文件大小 单位：MB
  max_size: 1
  # 日志文件保留天数
  max_age: 30
  # 日志文件分割数量上限
  max_backups: 10
# Redis 配置
redis:
  # Redis 地址
  host: localhost
  # Redis 端口
  port: 6379
  # Redis 密码
  password: ""
  # 指定数据库
  db: 0

mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456
  database: "ws_home"
  max_open_conns: 200
  max_idle_conns: 50

# 雪花算法配置
snowflake:
  # 起始时间
  start_time: "2024-10-19"
  # 机器ID
  machine_id: 1

# 认证授权
auth:
  # 密钥
  jwt_secret: "123456"
  # 过期时间 单位：分钟
  jwt_expire: 30
# 腾讯云 COS（对象存储） 配置
cos:
  access_key: ""
  secret_key: ""
  #  地域
  region: ""
  # 存储桶名称
  bucket: ""
  base_url: "https://www.example.com"
  # 预签名 url 过期时间 单位：秒
  sign_expire: 600
  # CDN 加速地址
  cdn_url: "https://www.xxx.com"
# 高德地图配置
amap:
  key: "your_amap_key"
  # 逆地理编码接口地址
  regeo_url: "https://restapi.amap.com/v3/geocode/regeo"